pipeline {
  agent any
  stages {
    stage('Build') {
        steps {
            sh 'docker build -t ${env.JOB_NAME} -f ./frontend/' 
        }
    }

    stage('Tag') {
        steps { 
            sh 'docker tag ${BUILD_TAG} 559559966174.dkr.ecr.us-east-2.amazonaws.com/${BUILD_TAG}'
        }
    }

    stage('Deploy To ECR') {
        steps {
        docker.withRegistry("https://559559966174.dkr.ecr.us-east-2.amazonaws.com", "ecr:us-east-2:credential-id"){ 
        docker.image("${BUILD_TAG}}").push()
        }
    }
  }
}