pipeline {
   
    stages {
        stage('Build 🛠️') {
            steps{
            sh 'docker build -t todo-frontend .' 
            sh 'docker tag todo-frontend:$BUILD_NUMBER 559559966174.dkr.ecr.us-east-2.amazonaws.com/todo-frontend:$BUILD_NUMBER'
            }
        }
        stage('Test 🔬') {
            steps {
                echo 'Testing Sonarqube'
            }
        }
    
        stage('Deploy To AWS ECR 📦') {
            steps {
            sh 'docker push 559559966174.dkr.ecr.us-east-2.amazonaws.com/todo-frontend:$BUILD_NUMBER'
            }
        }
    }