pipeline {
  agent any
  stages {
    stage('Build') {
        steps {
            sh 'cd frontend/'  
            sh 'docker build -t todo-frontend .' 
        }
    }

    stage('Tag') {
        steps { 
            sh 'docker tag todo-frontend:latest 559559966174.dkr.ecr.us-east-2.amazonaws.com/todo-frontend:latest'
        }
    }

    stage('Deploy') {
      steps { 
          sh 'docker push 559559966174.dkr.ecr.us-east-2.amazonaws.com/todo-frontend:latest' 
      }
    }
  }
}