version: "3"
services:
  frontend-app: #frontend-svc
    image: taufiq14s/todo-frontend
    stdin_open: true
    ports:
      - "80:80"
    networks:
      - mern-app
    env_file: ./.env
    environment:
      - API_SERVER=api-server
      - API_PORT=4000
  api-server: #backend-svc
    image: taufiq14s/todo-backend
    ports:
      - "4000:4000"
    networks:
      - mern-app
    depends_on:
      - mongo
    env_file: ./.env
    environment:
      - DB_SERVER=mongo
      - DB_PORT=27017
  mongo: #mongo-svc
    image: taufiq14s/todo-mongo  #todo-mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
